name: Minimal Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK Components
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-34"
          sdkmanager "build-tools;34.0.0"

      - name: Setup Gradle Wrapper
        run: |
          chmod +x gradlew
          ./gradlew --version

      - name: Create Minimal gradle.properties
        run: |
          cat > gradle.properties << EOF
          org.gradle.daemon=false
          org.gradle.caching=false
          org.gradle.parallel=false
          android.useAndroidX=true
          android.enableJetifier=true
          EOF

      - name: Test Basic Gradle
        run: |
          echo "Testing basic Gradle functionality..."
          ./gradlew projects --quiet
          echo "Basic test passed"

      - name: Try Clean
        run: |
          echo "Trying clean..."
          ./gradlew clean --quiet
          echo "Clean successful"

      - name: Try Build Debug
        run: |
          echo "Trying debug build..."
          ./gradlew assembleDebug --quiet --stacktrace
          echo "Debug build completed"

      - name: Check APK
        run: |
          echo "Checking for APK..."
          if [ -f "app/build/outputs/apk/debug/app-debug.apk" ]; then
            echo "✅ APK found: app/build/outputs/apk/debug/app-debug.apk"
            ls -la app/build/outputs/apk/debug/
          else
            echo "❌ APK not found"
            find . -name "*.apk" -type f
          fi

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk