name: Build ClaudecodeUI APK

on:
  push:
    branches: [ main, master ]
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      build-type:
        description: "نوع البناء"
        required: true
        default: "release"
        type: choice
        options: [release, debug]

permissions:
  contents: write

jobs:
  build-apk:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ inputs.build-type || 'release' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set Gradle Permissions
        run: chmod +x gradlew

      - name: Install Android SDK components
        run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build APK
        run: ./gradlew assemble${{ env.BUILD_TYPE^ }} --no-daemon

      - name: Locate APK
        id: apk
        run: |
          APK_PATH=$(find app/build/outputs/apk/${{ env.BUILD_TYPE }} -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "لم يتم العثور على APK" && exit 1
          fi
          echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT
          echo "Found APK at: $APK_PATH"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: claudecodeui-${{ env.BUILD_TYPE }}.apk
          path: ${{ steps.apk.outputs.apk_path }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.apk.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}